export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const GETORDERCOUNTBY_PICKUPSLOTS_START =
  "GETORDERCOUNTBY_PICKUPSLOTS_START";
export const GETORDERCOUNTBY_PICKUPSLOTS_SUCCESS =
  "GETORDERCOUNTBY_PICKUPSLOTS_SUCCESS";
export const GETORDERCOUNTBY_PICKUPSLOTS_FAILURE =
  "GETORDERCOUNTBY_PICKUPSLOTS_FAILURE";

export const GETACTIVE_ORDER_START = "GETACTIVE_ORDER_START";
export const GETACTIVE_ORDER_SUCCESS = "GETACTIVE_ORDER_SUCCESS";
export const GETACTIVE_ORDER_FAILURE = "GETACTIVE_ORDER_FAILURE";

export const UPDATE_ORDER_STATUS_START = "UPDATE_ORDER_STATUS_START";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAILURE = "UPDATE_ORDER_STATUS_FAILURE";

export const UPDATE_ORDER_ITEM_STATUS_START = "UPDATE_ORDER_ITEM_STATUS_START";
export const UPDATE_ORDER_ITEM_STATUS_SUCCESS =
  "UPDATE_ORDER_ITEM_STATUS_SUCCESS";
export const UPDATE_ORDER_ITEM_STATUS_FAILURE =
  "UPDATE_ORDER_ITEM_STATUS_FAILURE";

export const GET_ORDER_DETAILS_START = "GET_ORDER_DETAILS_START";
export const GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS";
export const GET_ORDER_DETAILS_FAILURE = "GET_ORDER_DETAILS_FAILURE";

export const GET_CONTACT_US_START = "GET_CONTACT_US_START";
export const GET_CONTACT_US_SUCCESS = "GET_CONTACT_US_SUCCESS";
export const GET_CONTACT_US_FAILURE = "GET_CONTACT_US_FAILURE";

export const GET_POS_ORDER_DETAILS_START = "GET_POS_ORDER_DETAILS_START";
export const GET_POS_ORDER_DETAILS_SUCCESS = "GET_POS_ORDER_DETAILS_SUCCESS";
export const GET_POS_ORDER_DETAILS_FAILURE = "GET_POS_ORDER_DETAILS_FAILURE";

export const CHANGE_PASSWORD_STORE_USER_START =
  "CHANGE_PASSWORD_STORE_USER_START";
export const CHANGE_PASSWORD_STORE_USER_SUCCESS =
  "CHANGE_PASSWORD_STORE_USER_SUCCESS";
export const CHANGE_PASSWORD_STORE_USER_FAILURE =
  "CHANGE_PASSWORD_STORE_USER_FAILURE";

export const GET_MATCHED_BASKETS_FOR_ECOMM_ORDER_START =
  "GET_MATCHED_BASKETS_FOR_ECOMM_ORDER_START";
export const GET_MATCHED_BASKETS_FOR_ECOMM_ORDER_SUCCESS =
  "GET_MATCHED_BASKETS_FOR_ECOMM_ORDER_SUCCESS";
export const GET_MATCHED_BASKETS_FOR_ECOMM_ORDER_FAILURE =
  "GET_MATCHED_BASKETS_FOR_ECOMM_ORDER_FAILURE";

export const ACCEPT_WIC_ORDER_START = "ACCEPT_WIC_ORDER_START";
export const ACCEPT_WIC_ORDER_SUCCESS = "ACCEPT_WIC_ORDER_SUCCESS";
export const ACCEPT_WIC_ORDER_FAILURE = "ACCEPT_WIC_ORDER_FAILURE";

export const PROCESS_ORDER_START = "PROCESS_ORDER_START";
export const PROCESS_ORDER_SUCCESS = "PROCESS_ORDER_SUCCESS";
export const PROCESS_ORDER_FAILURE = "PROCESS_ORDER_FAILURE";

export const GET_DISCOUNT_COUPONS_LIST_START =
  "GET_DISCOUNT_COUPONS_LIST_START";
export const GET_DISCOUNT_COUPONS_LIST_SUCCESS =
  "GET_DISCOUNT_COUPONS_LIST_SUCCESS";
export const GET_DISCOUNT_COUPONS_LIST_FAILURE =
  "GET_DISCOUNT_COUPONS_LIST_FAILURE";

// --------------------------------------------------------------
// RSA- API

export const GET_AWS_INFO_START = "GET_AWS_INFO_START";
export const GET_AWS_INFO_SUCCESS = "GET_AWS_INFO_SUCCESS";
export const GET_AWS_INFO_FAILURE = "GET_AWS_INFO_FAILURE";

export const GET_BASKET_DATA_START = "GET_BASKET_DATA_START";
export const GET_BASKET_DATA_SUCCESS = "GET_BASKET_DATA_SUCCESS";
export const GET_BASKET_DATA_FAILURE = "GET_BASKET_DATA_FAILURE";

export const GET_PRODUCT_PRICE_START = "GET_PRODUCT_PRICE_START";
export const GET_PRODUCT_PRICE_SUCCESS = "GET_PRODUCT_PRICE_SUCCESS";
export const GET_PRODUCT_PRICE_FAILURE = "GET_PRODUCT_PRICE_FAILURE";

export const AOG_GET_PRODUCTS_START = "AOG_GET_PRODUCTS_START";
export const AOG_GET_PRODUCTS_SUCCESS = "AOG_GET_PRODUCTS_SUCCESS";
export const AOG_GET_PRODUCTS_FAILURE = "AOG_GET_PRODUCTS_FAILURE";

export const ADD_SUBSTITUTION_ITEM_START = "ADD_SUBSTITUTION_ITEM_START";
export const ADD_SUBSTITUTION_ITEM_SUCCESS = "ADD_SUBSTITUTION_ITEM_SUCCESS";
export const ADD_SUBSTITUTION_ITEM_FAILURE = "ADD_SUBSTITUTION_ITEM_FAILURE";

export const CANCEL_SUBSTITUTION_ITEM_START = "CANCEL_SUBSTITUTION_ITEM_START";
export const CANCEL_SUBSTITUTION_ITEM_SUCCESS =
  "CANCEL_SUBSTITUTION_ITEM_SUCCESS";
export const CANCEL_SUBSTITUTION_ITEM_FAILURE =
  "CANCEL_SUBSTITUTION_ITEM_FAILURE";

export const AOG_REPLACE_UPC_INORDER_START = "AOG_REPLACE_UPC_INORDER_START";
export const AOG_REPLACE_UPC_INORDER_SUCCESS =
  "AOG_REPLACE_UPC_INORDER_SUCCESS";
export const AOG_REPLACE_UPC_INORDER_FAILURE =
  "AOG_REPLACE_UPC_INORDER_FAILURE";

export const ADD_PRODUCT_IMAGE_START = "ADD_PRODUCT_IMAGE_START";
export const ADD_PRODUCT_IMAGE_SUCCESS = "ADD_PRODUCT_IMAGE_SUCCESS";
export const ADD_PRODUCT_IMAGE_FAILURE = "ADD_PRODUCT_IMAGE_FAILURE";

export const AOG_ORDER_CANCEL_BY_PICKER_START =
  "AOG_ORDER_CANCEL_BY_PICKER_START";
export const AOG_ORDER_CANCEL_BY_PICKER_SUCCESS =
  "AOG_ORDER_CANCEL_BY_PICKER_SUCCESS";
export const AOG_ORDER_CANCEL_BY_PICKER_FAILURE =
  "AOG_ORDER_CANCEL_BY_PICKER_FAILURE";

export const SEARCH_ORDER_DETAILS_START = "SEARCH_ORDER_DETAILS_START";
export const SEARCH_ORDER_DETAILS_SUCCESS = "SEARCH_ORDER_DETAILS_SUCCESS";
export const SEARCH_ORDER_DETAILS_FAILURE = "SEARCH_ORDER_DETAILS_FAILURE";

export const ADD_PRODUCT_IN_ORDER_ITEM_START =
  "ADD_PRODUCT_IN_ORDER_ITEM_START";
export const ADD_PRODUCT_IN_ORDER_ITEM_SUCCESS =
  "ADD_PRODUCT_IN_ORDER_ITEM_SUCCESS";
export const ADD_PRODUCT_IN_ORDER_ITEM_FAILURE =
  "ADD_PRODUCT_IN_ORDER_ITEM_FAILURE";

export const IMAGE_UPLOAD_START = "IMAGE_UPLOAD_START";
export const IMAGE_UPLOAD_SUCCESS = "IMAGE_UPLOAD_SUCCESS";
export const IMAGE_UPLOAD_FAILURE = "IMAGE_UPLOAD_FAILURE";
// -----------------------------------------------------------------------

export const DUMMY_START = "DUMMY_START";
export const DUMMY_SUCCESS = "DUMMY_SUCCESS";
export const DUMMY_FAILURE = "DUMMY_FAILURE";
