export const GET_CATEGORIES_START = "GET_CATEGORIES_START";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const GET_EACH_CATEGORY_START = "GET_EACH_CATEGORY_START";
export const GET_EACH_CATEGORY_SUCCESS = "GET_EACH_CATEGORY_SUCCESS";
export const GET_EACH_CATEGORY_FAILURE = "GET_EACH_CATEGORY_FAILURE";

// ----------------------------------------------------------------------------------
export const DUMMY_START = "DUMMY_START";
export const DUMMY_SUCCESS = "DUMMY_SUCCESS";
export const DUMMY_FAILURE = "DUMMY_FAILURE";
